//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Framework_Graphic_RenderQueueOverriderWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Framework.Graphic.RenderQueueOverrider), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("OverrideRenderQueue", get_OverrideRenderQueue, set_OverrideRenderQueue);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OverrideRenderQueue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Framework.Graphic.RenderQueueOverrider obj = (Framework.Graphic.RenderQueueOverrider)o;
			int ret = obj.OverrideRenderQueue;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OverrideRenderQueue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OverrideRenderQueue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Framework.Graphic.RenderQueueOverrider obj = (Framework.Graphic.RenderQueueOverrider)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.OverrideRenderQueue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OverrideRenderQueue on a nil value");
		}
	}
}

